In [1]:
import pandas as pd

In [8]:
fred_endpoint = "https://fred.stlouisfed.org/graph/fredgraph.csv?id="
cpi_meonic = "CPIAUCSL"
un_menomic = "UNRATE"

In [10]:
fred_endpoint + cpi_meonic

'https://fred.stlouisfed.org/graph/fredgraph.csv?id=CPIAUCSL'

In [13]:
un_raw = pd.read_csv(fred_endpoint + un_menomic)
cpi_raw = pd.read_csv(fred_endpoint + cpi_meonic)

In [15]:
un_raw.head()

  observation_date  UNRATE
0       1948-01-01     3.4
1       1948-02-01     3.8
2       1948-03-01     4.0
3       1948-04-01     3.9
4       1948-05-01     3.5

In [16]:
cpi_raw.head()

  observation_date  CPIAUCSL
0       1947-01-01     21.48
1       1947-02-01     21.62
2       1947-03-01     22.00
3       1947-04-01     22.00
4       1947-05-01     21.95

In [17]:
un_raw.dtypes

observation_date     object
UNRATE              float64
dtype: object

In [19]:
print('Missing values in each raw file:')
print('UNRATE (unemployment rate):', un_raw.isna().sum().to_dict())
print('CPIAUCSL (CPI level):', cpi_raw.isna().sum().to_dict())

Missing values in each raw file:
UNRATE (unemployment rate): {'observation_date': 0, 'UNRATE': 1}
CPIAUCSL (CPI level): {'observation_date': 0, 'CPIAUCSL': 1}

In [20]:
unemployment = un_raw.rename(
    columns={
        'observation_date' : 'date',
        'UNRATE' : 'unemployment_rate',
    }
).copy() #Create deep copyy - ensures unemployemnt is SPERATE from un_raw

cpi = cpi_raw.rename(
    columns={
        'observation_date' : 'date',
        'CPIAUCSL' : 'cpi',
    }
).copy()

In [23]:
unemployment.head()

        date  unemployment_rate
0 1948-01-01                3.4
1 1948-02-01                3.8
2 1948-03-01                4.0
3 1948-04-01                3.9
4 1948-05-01                3.5

In [24]:
unemployment['date'] = pd.to_datetime(unemployment['date'])
cpi['date'] = pd.to_datetime(cpi['date'])

unemployment = unemployment.sort_values('date')
cpi = cpi.sort_values('date')

In [26]:
unemployment.tail()

          date  unemployment_rate
940 2026-05-01                4.3
941 2026-06-01                4.2
942 2026-07-01                4.1
943 2026-08-01                4.1
944 2026-09-01                4.2

In [27]:
print('Unemployment dates - all unique:', unemployment['date'].is_unique)
print('CPI dates - all unique:', cpi['date'].is_unique)
print('Unemployment dates - sample size:', len(unemployment))
print('CPI- sample size:', len(cpi))

Unemployment dates - all unique: True
CPI dates - all unique: True
Unemployment dates - sample size: 945
CPI- sample size: 956

In [28]:
print('Unemployment start is', unemployment['date'].min(),
      ' and end is ', unemployment['date'].max())
print('CPI start is ', cpi['date'].min(),
      ' and end is ', cpi['date'].max())

Unemployment start is 1948-01-01 00:00:00  and end is  2026-09-01 00:00:00
CPI start is  1947-01-01 00:00:00  and end is  2026-08-01 00:00:00